type
  TActionManager=class(TCustomActionManager)
  private
   FAction             :TCustomAction;
   FActionBars         :TActionBars;
   FCompareCaption     :string;
   FCompareProc        :TActionProc;
   FDisabledImageChangeLink:TChangeLink;
   FDisabledImages     :TCustomImageList;
   FFoundClient        :TActionClientItem;
   FLinkedActionLists  :TActionListCollection;
   FDefaultActionBars  :TActionBars;
   FFileName           :TFileName;
   FLargeDisabledImageChangeLink:TChangeLink;
   FLargeDisabledImages:TCustomImageList;
   FLargeImageChangeLink:TChangeLink;
   FLargeImages        :TCustomImageList;
   FLoading            :Boolean;
   FPrioritySchedule   :TStringList;
   FSaved              :Boolean;
   FOnGetBarItemClass  :TGetBarItemClassEvent;
   FOnGetBarsClass     :TGetBarsClassEvent;
   FOnGetClientItemClass:TGetClientItemClassEvent;
   FOnGetClientsClass  :TGetClientsClassEvent;
   FOnStyleChanged     :TStyleChanged;
   FStyle              :TActionBarStyle;
   FOnGetCommandPropertiesClass:TGetCommandPropertiesClassEvent;
   FActions            :TList;
   FImageChangeLink    :TChangeLink;
   FImages             :TCustomImageList;
   FOnChange           :TNotifyEvent;
   FOnExecute          :TActionEvent;
   FOnUpdate           :TActionEvent;
   FState              :TActionListState;
   FOnStateChange      :TNotifyEvent;
   FOwner              :TComponent;
   FName               :TComponentName;
   FTag                :NativeInt;
   FComponents         :TList;
   FFreeNotifies       :TList;
   FDesignInfo         :Integer;
   FComponentState     :TComponentState;
   FVCLComObject       :Pointer;
   FObservers          :TObservers;
   FSortedComponents   :TList;
   function GetAction(Index: Integer): TContainedAction;
   procedure SetAction(Index: Integer; Value: TContainedAction);
   function GetComponent(AIndex: Integer): TComponent;
  protected
   FComponentStyle     :TComponentStyle;
  public
   constructor Create(AOwner: TComponent);
   class destructor Destroy;
   function GetActionClientItemClass: TActionClientItemClass;
   function GetCommandPropertiesClass(AnItem: TActionClientItem): TCommandPropertiesClass;
   function AddAction(AnAction: TCustomAction; AClient: TActionClient; After: Boolean): TActionClientItem;
   function AddCategory(ACategory: string; AClient: TActionClient; After: Boolean): TActionClientItem;
   function AddSeparator(AnItem: TActionClientItem; After: Boolean): TActionClientItem;
   procedure Assign(Source: TPersistent);
   (basic) procedure DeleteActionItems;
   procedure DeleteItem(Caption: string);
   function FindItemByCaption(ACaption: string): TActionClientItem;
   function FindItemByAction(Action: TCustomAction): TActionClientItem;
   procedure LoadFromFile(const Filename: string);
   procedure LoadFromStream(S: TStream);
   procedure ResetActionBar(Index: Integer);
   procedure ResetUsageData;
   procedure SaveToFile(const Filename: string);
   procedure SaveToStream(S: TStream);
   procedure AfterConstruction;
   constructor Create(AOwner: TComponent);
   class destructor Destroy;
   function ExecuteAction(Action: TBasicAction): Boolean;
   procedure GetChildren(Proc: TGetChildProc = procedure(Child: TComponent) of object; Root: TComponent);
   function GetEnumerator: TActionListEnumerator;
   function IsShortCut(var Message: TWMKey): Boolean;
   function UpdateAction(Action: TBasicAction): Boolean;
   constructor Create(AOwner: TComponent);
   class destructor Destroy;
   procedure BeforeDestruction;
   procedure DestroyComponents;
   procedure Destroying;
   function ExecuteAction(Action: TBasicAction): Boolean;
   function FindComponent(const AName: string): TComponent;
   procedure FreeNotification(AComponent: TComponent);
   procedure RemoveFreeNotification(AComponent: TComponent);
   procedure FreeOnRelease;
   function GetEnumerator: TComponentEnumerator;
   function GetParentComponent: TComponent;
   function GetNamePath: string;
   function HasParent: Boolean;
   procedure InsertComponent(AComponent: TComponent);
   procedure RemoveComponent(AComponent: TComponent);
   procedure SetSubComponent(IsSubComponent: Boolean);
   function SafeCallException(ExceptObject: TObject; ExceptAddr: Pointer): HRESULT;
   function UpdateAction(Action: TBasicAction): Boolean;
   function IsImplementorOf(const I: IInterface): Boolean;
   function ReferenceInterface(const I: IInterface; Operation: TOperation): Boolean;
   class destructor Destroy;
   procedure Assign(Source: TPersistent);
   function GetNamePath: string;
   constructor Create;
   procedure Free;
   class function InitInstance(Instance: Pointer): TObject;
   procedure CleanupInstance;
   function ClassType: TClass;
   class function ClassName: string;
   class function ClassNameIs(const Name: string): Boolean;
   class function ClassParent: TClass;
   class function ClassInfo: Pointer;
   class function InstanceSize: Integer;
   class function InheritsFrom(AClass: TClass): Boolean;
   class function MethodAddress(const Name: ShortString): Pointer;
   class function MethodAddress(const Name: string): Pointer;
   class function MethodName(Address: Pointer): string;
   class function QualifiedClassName: string;
   function FieldAddress(const Name: ShortString): Pointer;
   function FieldAddress(const Name: string): Pointer;
   function GetInterface(const IID: TGUID; out Obj): Boolean;
   class function GetInterfaceEntry(const IID: TGUID): PInterfaceEntry;
   class function GetInterfaceTable: PInterfaceTable;
   class function UnitName: string;
   class function UnitScope: string;
   function Equals(Obj: TObject): Boolean;
   function GetHashCode: Integer;
   function ToString: string;
   function SafeCallException(ExceptObject: TObject; ExceptAddr: Pointer): HRESULT;
   procedure AfterConstruction;
   procedure BeforeDestruction;
   procedure Dispatch(var Message);
   procedure DefaultHandler(var Message);
   class function NewInstance: TObject;
   procedure FreeInstance;
   class destructor Destroy;
   property ActionBars: TActionBars;
   property DefaultActionBars: TActionBars;
   property DisabledImages: TCustomImageList;
   property LargeDisabledImages: TCustomImageList;
   property LargeImages: TCustomImageList;
   property LinkedActionLists: TActionListCollection;
   property FileName: TFileName;
   property Images: TCustomImageList;
   property PrioritySchedule: TStringList;
   property Style: TActionBarStyle;
   property OnStyleChanged: TStyleChanged;
   property ActionCount: Integer;
   property Images: TCustomImageList;
   property State: TActionListState;
   property OnStateChange: TNotifyEvent;
   property ComObject: IInterface;
   property ComponentCount: Integer;
   property ComponentIndex: Integer;
   property ComponentState: TComponentState;
   property ComponentStyle: TComponentStyle;
   property DesignInfo: Integer;
   property Owner: TComponent;
   property VCLComObject: Pointer;
   property Observers: TObservers;
  published
   property FileName: TFileName;
   property ActionBars: TActionBars;
   property DisabledImages: TCustomImageList;
   property LargeDisabledImages: TCustomImageList;
   property LargeImages: TCustomImageList;
   property LinkedActionLists: TActionListCollection;
   property Images: TCustomImageList;
   property PrioritySchedule: TStringList;
   property State: TActionListState;
   property Style: TActionBarStyle;
   property OnChange: TNotifyEvent;
   property OnExecute: TActionEvent;
   property OnGetBarItemClass: TGetBarItemClassEvent;
   property OnGetBarsClass: TGetBarsClassEvent;
   property OnGetClientsClass: TGetClientsClassEvent;
   property OnGetClientItemClass: TGetClientItemClassEvent;
   property OnGetCommandPropertiesClass: TGetCommandPropertiesClassEvent;
   property OnUpdate: TActionEvent;
   property OnStateChange: TNotifyEvent;
   property OnStyleChanged: TStyleChanged;
   property Name: TComponentName;
   property Tag: NativeInt;
  end;
