type
  TThemedColorMap=class(TCustomActionBarColorMap)
  private
   FActionBars         :TList;
   FBtnSelectedColor   :TColor;
   FBtnFrameColor      :TColor;
   FBtnSelectedFont    :TColor;
   FColor              :TColor;
   FDisabledColor      :TColor;
   FDisabledFontColor  :TColor;
   FDisabledFontShadow :TColor;
   FFontColor          :TColor;
   FHotColor           :TColor;
   FShadowColor        :TColor;
   FHotFontColor       :TColor;
   FUnusedColor        :TColor;
   FSelectedFontColor  :TColor;
   FSelectedColor      :TColor;
   FHighlightColor     :TColor;
   FDesignFocus        :TColor;
   FMenuColor          :TColor;
   FFrameTopLeftInner  :TColor;
   FFrameTopLeftOuter  :TColor;
   FFrameBottomRightInner:TColor;
   FFrameBottomRightOuter:TColor;
   FOnColorChange      :TNotifyEvent;
   FOwner              :TComponent;
   FName               :TComponentName;
   FTag                :NativeInt;
   FComponents         :TList;
   FFreeNotifies       :TList;
   FDesignInfo         :Integer;
   FComponentState     :TComponentState;
   FVCLComObject       :Pointer;
   FObservers          :TObservers;
   FSortedComponents   :TList;
   function GetComponent(AIndex: Integer): TComponent;
  protected
   FComponentStyle     :TComponentStyle;
  public
   procedure UpdateColors;
   constructor Create(AOwner: TComponent);
   class destructor Destroy;
   procedure Assign(Source: TPersistent);
   procedure UpdateColors;
   constructor Create(AOwner: TComponent);
   class destructor Destroy;
   procedure BeforeDestruction;
   procedure DestroyComponents;
   procedure Destroying;
   function ExecuteAction(Action: TBasicAction): Boolean;
   function FindComponent(const AName: string): TComponent;
   procedure FreeNotification(AComponent: TComponent);
   procedure RemoveFreeNotification(AComponent: TComponent);
   procedure FreeOnRelease;
   function GetEnumerator: TComponentEnumerator;
   function GetParentComponent: TComponent;
   function GetNamePath: string;
   function HasParent: Boolean;
   procedure InsertComponent(AComponent: TComponent);
   procedure RemoveComponent(AComponent: TComponent);
   procedure SetSubComponent(IsSubComponent: Boolean);
   function SafeCallException(ExceptObject: TObject; ExceptAddr: Pointer): HRESULT;
   function UpdateAction(Action: TBasicAction): Boolean;
   function IsImplementorOf(const I: IInterface): Boolean;
   function ReferenceInterface(const I: IInterface; Operation: TOperation): Boolean;
   class destructor Destroy;
   procedure Assign(Source: TPersistent);
   function GetNamePath: string;
   constructor Create;
   procedure Free;
   class function InitInstance(Instance: Pointer): TObject;
   procedure CleanupInstance;
   function ClassType: TClass;
   class function ClassName: string;
   class function ClassNameIs(const Name: string): Boolean;
   class function ClassParent: TClass;
   class function ClassInfo: Pointer;
   class function InstanceSize: Integer;
   class function InheritsFrom(AClass: TClass): Boolean;
   class function MethodAddress(const Name: ShortString): Pointer;
   class function MethodAddress(const Name: string): Pointer;
   class function MethodName(Address: Pointer): string;
   class function QualifiedClassName: string;
   function FieldAddress(const Name: ShortString): Pointer;
   function FieldAddress(const Name: string): Pointer;
   function GetInterface(const IID: TGUID; out Obj): Boolean;
   class function GetInterfaceEntry(const IID: TGUID): PInterfaceEntry;
   class function GetInterfaceTable: PInterfaceTable;
   class function UnitName: string;
   class function UnitScope: string;
   function Equals(Obj: TObject): Boolean;
   function GetHashCode: Integer;
   function ToString: string;
   function SafeCallException(ExceptObject: TObject; ExceptAddr: Pointer): HRESULT;
   procedure AfterConstruction;
   procedure BeforeDestruction;
   procedure Dispatch(var Message);
   procedure DefaultHandler(var Message);
   class function NewInstance: TObject;
   procedure FreeInstance;
   class destructor Destroy;
   property BtnFrameColor: TColor;
   property BtnSelectedColor: TColor;
   property BtnSelectedFont: TColor;
   property Color: TColor;
   property DesignFocus: TColor;
   property DisabledColor: TColor;
   property DisabledFontColor: TColor;
   property DisabledFontShadow: TColor;
   property FontColor: TColor;
   property FrameTopLeftInner: TColor;
   property FrameTopLeftOuter: TColor;
   property FrameBottomRightInner: TColor;
   property FrameBottomRightOuter: TColor;
   property HighlightColor: TColor;
   property HotColor: TColor;
   property HotFontColor: TColor;
   property MenuColor: TColor;
   property SelectedColor: TColor;
   property SelectedFontColor: TColor;
   property ShadowColor: TColor;
   property UnusedColor: TColor;
   property OnColorChange: TNotifyEvent;
   property ComObject: IInterface;
   property ComponentCount: Integer;
   property ComponentIndex: Integer;
   property ComponentState: TComponentState;
   property ComponentStyle: TComponentStyle;
   property DesignInfo: Integer;
   property Owner: TComponent;
   property VCLComObject: Pointer;
   property Observers: TObservers;
  published
   property ShadowColor: TColor;
   property Color: TColor;
   property DisabledColor: TColor;
   property DisabledFontColor: TColor;
   property DisabledFontShadow: TColor;
   property FontColor: TColor;
   property HighlightColor: TColor;
   property HotColor: TColor;
   property HotFontColor: TColor;
   property MenuColor: TColor;
   property FrameTopLeftInner: TColor;
   property FrameTopLeftOuter: TColor;
   property FrameBottomRightInner: TColor;
   property FrameBottomRightOuter: TColor;
   property BtnFrameColor: TColor;
   property BtnSelectedColor: TColor;
   property BtnSelectedFont: TColor;
   property SelectedColor: TColor;
   property SelectedFontColor: TColor;
   property UnusedColor: TColor;
   property OnColorChange: TNotifyEvent;
   property Name: TComponentName;
   property Tag: NativeInt;
  end;
