    {$ifdef VER290}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
     {$define DELPHI_XE2_UP}
     {$define DELPHI_XE3_UP}
     {$define DELPHI_XE4_UP}
     {$define DELPHI_XE5_UP}
     {$define DELPHI_XE6_UP}
     {$define DELPHI_XE7_UP}
     {$define DELPHI_XE8_UP}
	{$endif}

    {$ifdef VER280}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
     {$define DELPHI_XE2_UP}
     {$define DELPHI_XE3_UP}
     {$define DELPHI_XE4_UP}
     {$define DELPHI_XE5_UP}
     {$define DELPHI_XE6_UP}
     {$define DELPHI_XE7_UP}
	{$endif}

    {$ifdef VER270}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
     {$define DELPHI_XE2_UP}
     {$define DELPHI_XE3_UP}
     {$define DELPHI_XE4_UP}	 	 
     {$define DELPHI_XE5_UP}	
     {$define DELPHI_XE6_UP}	 
	{$endif}   
	
    {$ifdef VER260}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
     {$define DELPHI_XE2_UP}
     {$define DELPHI_XE3_UP}
     {$define DELPHI_XE4_UP}	 
     {$define DELPHI_XE5_UP}	
	{$endif}   
	
    {$ifdef VER250}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
     {$define DELPHI_XE2_UP}
     {$define DELPHI_XE3_UP}
     {$define DELPHI_XE4_UP}	 
    {$endif}    
	
	{$ifdef VER240}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
     {$define DELPHI_XE2_UP}
     {$define DELPHI_XE3_UP}
    {$endif}

    {$ifdef VER230}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
     {$define DELPHI_XE2_UP}
    {$endif}

    {$ifdef VER220}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
    {$endif}

    {$ifdef VER210}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
    {$endif}

    {$ifdef VER200}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
    {$endif}

    {$ifdef VER190}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
    {$endif}

    {$ifdef VER180}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
     {$define DELPHI_10_UP}
    {$endif}

    {$ifdef VER170}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
     {$define DELPHI_9_UP}
    {$endif}

    {$ifdef VER160}        
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
     {$define DELPHI_8_UP}
    {$endif}

    {$ifdef VER150}        
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
     {$define DELPHI_7_UP}
    {$endif}

    {$ifdef VER140}
     {$define DELPHI_5_UP}
     {$define DELPHI_6_UP}
    {$endif}

    {$ifdef VER130}
     {$define DELPHI_5_UP}
    {$endif}

    {.$DEFINE mbXP_Lib}